### ISSUE TITLE
Comparison Vue 3 vs. Vue 2 - repo for Vue 2?

### ISSUE THREAD

**Issue by brucou** [ShetlandJ/Vue3Todo#5]
This is not a proper issue but more of a question. I am reviewing currently the Vue3Todo repo, and in particular the colored code comparison of Vue2 vs. Vue3. I was however wondering where to have a look at the similar Vue2 codebase from which the comparison originates?

**Comment by ShetlandJ** [comment]
Hi pal,

If you are talking about the colour-compared Pet List component, they're both in this repo:

https://github.com/ShetlandJ/Vue3Todo/blob/master/src/components/PetListV2.vue
https://github.com/ShetlandJ/Vue3Todo/blob/master/src/components/PetListV3.vue

**Comment by brucou** [comment]
Thanks! I missed that apparently. Greatly appreciated. Writing an
article about your video, so wanted to include both codes. Will let
you know when the article is published

On 9/29/19, James <notifications@github.com> wrote:
> Hi pal,
>
> If you are talking about the colour-compared Pet List component, they're
> both in this repo:
>
> https://github.com/ShetlandJ/Vue3Todo/blob/master/src/components/PetListV2.vue
> https://github.com/ShetlandJ/Vue3Todo/blob/master/src/components/PetListV3.vue
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ShetlandJ/Vue3Todo/issues/5#issuecomment-536229906


-- 
---

**Comment by brucou** [comment]
Article: https://www.infoq.com/news/2019/09/comparison-vue3-composition-api/
